apiVersion: v1
kind: Secret
metadata:
  name: pronestheus-secrets
type: Opaque
data:
  PRONESTHEUS_NEST_CLIENT_ID: "<SECRET>"
  PRONESTHEUS_NEST_CLIENT_SECRET: "<SECRET>"
  PRONESTHEUS_NEST_PROJECT_ID: "<SECRET>"
  PRONESTHEUS_NEST_REFRESH_TOKEN: "<SECRET>"