apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-spammer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-spammer
  template:
    metadata:
      labels:
        app: log-spammer
    spec:
      containers:
        - name: log-spammer
          image: cryptotuga/log-spammer:latest
