---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheus
  - ../base/grafana
  - ../base/podinfo
  - ../base/loki
  - ../base/pronestheus
  - ../base/teslafi
