{
 "title": "Llano Nest Thermostat",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Nest Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nest Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nest_up{app=\"pronestheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nest Uptime Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "nest_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Home Health ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Humidity Levels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nest_humidity_percent{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsPykLOIuqpWD9fcesrLHxpMXQeA1lQotrN6KHe32IxcT5WvN2UkdMRSiWnBK2ZxG7ts-e94Ge2bqjVm10cTbiahw\"}",
     "legendFormat": "Upper Nest Thermostat"
    },
    {
     "expr": "nest_humidity_percent{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsw1Z-l4HQ6RjHtIF3AXCM6w9ANVanBJidzsP4nAOAzqWuI7Xdn0ztbbFRu7OIw63AV6pGoSLvLVbRwCWXkAhpp4Q\"}",
     "legendFormat": "Lower Nest Thermostat"
    }
   ]
  },
  {
   "title": "Heater / AC Overtime Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "nest_heating{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsPykLOIuqpWD9fcesrLHxpMXQeA1lQotrN6KHe32IxcT5WvN2UkdMRSiWnBK2ZxG7ts-e94Ge2bqjVm10cTbiahw\"}",
     "legendFormat": "Upper Nest Thermostat"
    },
    {
     "expr": "nest_heating{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsw1Z-l4HQ6RjHtIF3AXCM6w9ANVanBJidzsP4nAOAzqWuI7Xdn0ztbbFRu7OIw63AV6pGoSLvLVbRwCWXkAhpp4Q\"}",
     "legendFormat": "Lower Nest Thermostat"
    }
   ]
  },
  {
   "title": "Ambient Temperature (Fahrenheit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsPykLOIuqpWD9fcesrLHxpMXQeA1lQotrN6KHe32IxcT5WvN2UkdMRSiWnBK2ZxG7ts-e94Ge2bqjVm10cTbiahw\"} * 1.8 + 32",
     "legendFormat": "Upper Nest Thermostat"
    },
    {
     "expr": "nest_ambient_temperature_celsius{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsw1Z-l4HQ6RjHtIF3AXCM6w9ANVanBJidzsP4nAOAzqWuI7Xdn0ztbbFRu7OIw63AV6pGoSLvLVbRwCWXkAhpp4Q\"} * 1.8 + 32",
     "legendFormat": "Lower Nest Thermostat"
    }
   ]
  },
  {
   "title": "Humidity Levels",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nest_humidity_percent{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsPykLOIuqpWD9fcesrLHxpMXQeA1lQotrN6KHe32IxcT5WvN2UkdMRSiWnBK2ZxG7ts-e94Ge2bqjVm10cTbiahw\"}",
     "legendFormat": "Upper Nest Thermostat"
    },
    {
     "expr": "nest_humidity_percent{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsw1Z-l4HQ6RjHtIF3AXCM6w9ANVanBJidzsP4nAOAzqWuI7Xdn0ztbbFRu7OIw63AV6pGoSLvLVbRwCWXkAhpp4Q\"}",
     "legendFormat": "Lower Nest Thermostat"
    }
   ]
  },
  {
   "title": "Heater / AC Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nest_heating{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsPykLOIuqpWD9fcesrLHxpMXQeA1lQotrN6KHe32IxcT5WvN2UkdMRSiWnBK2ZxG7ts-e94Ge2bqjVm10cTbiahw\"}",
     "legendFormat": "Upper Nest Thermostat"
    },
    {
     "expr": "nest_heating{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsw1Z-l4HQ6RjHtIF3AXCM6w9ANVanBJidzsP4nAOAzqWuI7Xdn0ztbbFRu7OIw63AV6pGoSLvLVbRwCWXkAhpp4Q\"}",
     "legendFormat": "Lower Nest Thermostat"
    }
   ]
  },
  {
   "title": "Ambient Temperature (Fahrenheit)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsPykLOIuqpWD9fcesrLHxpMXQeA1lQotrN6KHe32IxcT5WvN2UkdMRSiWnBK2ZxG7ts-e94Ge2bqjVm10cTbiahw\"} * 1.8 + 32",
     "legendFormat": "Upper Nest Thermostat"
    },
    {
     "expr": "nest_ambient_temperature_celsius{id=\"enterprises/396702c9-d24c-437b-9319-c421801a120a/devices/AVPHwEsw1Z-l4HQ6RjHtIF3AXCM6w9ANVanBJidzsP4nAOAzqWuI7Xdn0ztbbFRu7OIw63AV6pGoSLvLVbRwCWXkAhpp4Q\"} * 1.8 + 32",
     "legendFormat": "Lower Nest Thermostat"
    }
   ]
  }
 ]
}