{
 "title": "Tesla Model Y",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Locked / Unlocked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_locked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_usable_battery_level", "legendFormat": "{{display_name}}" }
   ]
  },
  {
   "title": "Battery Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_usable_battery_level", "legendFormat": "{{display_name}}" }
   ]
  },
  {
   "title": "Charging Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_charge_port_led_color{teslafi_charge_port_led_color=\"None\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Speed (MPH)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_speed_kmh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Software Update",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_newVersionStatus{teslafi_newVersionStatus=\"available\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inside Car Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_inside_temperature * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outside Car Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_outside_temperature * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mins Until Fully Charged",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_time_to_full_charge_seconds / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Miles Driven",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_odometer_meter_total / 1609",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Spent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_charge_energy_added_kwh * 0.21",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_carState{teslafi_carState=\"Driving\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "Battery Percentage Overtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "teslafi_usable_battery_level", "legendFormat": "{{display_name}}" }
   ]
  },
  {
   "title": "Odometer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mi" } },
   "targets": [
    {
     "expr": "teslafi_odometer_meter_total / 1609",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Range Estimate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "miles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teslafi_battery_range_est_meter / 1609",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Percentage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_usable_battery_level", "legendFormat": "{{display_name}}" }
   ]
  },
  {
   "title": "Battery Heater Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_battery_heater_on", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Range Estimate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "miles" } },
   "targets": [
    {
     "expr": "teslafi_battery_range_est_meter / 1609",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Display On / Off",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "teslafi_center_display_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Car State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "targets": [
    { "expr": "teslafi_carState", "legendFormat": "{{teslafi_carState}}" }
   ]
  },
  {
   "title": "Charging State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    { "expr": "teslafi_charging_state", "legendFormat": "{{teslafi_charging_state}}" }
   ]
  }
 ]
}